import { MameHiExtractor } from "../dist";
import { resolve } from "path";

it('gground', async () => {
    const a = new MameHiExtractor(resolve(__dirname, '../demo-hiscores'))
    const extractor = await a.get('gground')
    expect(extractor?.extract().scores).toEqual({
        default: [
            { rank: 1, score: 10000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 2, score: 9000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 3, score: 8000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 4, score: 7000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 5, score: 6000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 6, score: 5000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 7, score: 4000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 8, score: 3000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 9, score: 2000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 10, score: 1000, name: '', extra: { round: 1, stage: 1 } },
            { rank: 11, score: 995, name: 'ABC', extra: { round: 4, stage: 6 } },
            { rank: 12, score: 985, name: 'Z.Y', extra: { round: 1, stage: 6 } },
            { rank: 13, score: 970, name: '', extra: { round: 1, stage: 1 } },
            { rank: 14, score: 960, name: '', extra: { round: 1, stage: 1 } },
            { rank: 15, score: 950, name: '', extra: { round: 1, stage: 1 } },
            { rank: 16, score: 940, name: '', extra: { round: 1, stage: 1 } },
            { rank: 17, score: 930, name: '', extra: { round: 1, stage: 1 } },
            { rank: 18, score: 920, name: '', extra: { round: 1, stage: 1 } },
            { rank: 19, score: 910, name: '', extra: { round: 1, stage: 1 } },
            { rank: 20, score: 900, name: '', extra: { round: 1, stage: 1 } },
            { rank: 21, score: 890, name: '', extra: { round: 1, stage: 1 } },
            { rank: 22, score: 880, name: '', extra: { round: 1, stage: 1 } },
            { rank: 23, score: 870, name: '', extra: { round: 1, stage: 1 } },
            { rank: 24, score: 860, name: '', extra: { round: 1, stage: 1 } },
            { rank: 25, score: 850, name: '', extra: { round: 1, stage: 1 } },
            { rank: 26, score: 840, name: '', extra: { round: 1, stage: 1 } },
            { rank: 27, score: 830, name: '', extra: { round: 1, stage: 1 } },
            { rank: 28, score: 820, name: '', extra: { round: 1, stage: 1 } },
            { rank: 29, score: 810, name: '', extra: { round: 1, stage: 1 } },
            { rank: 30, score: 800, name: '', extra: { round: 1, stage: 1 } },
            { rank: 31, score: 790, name: '', extra: { round: 1, stage: 1 } },
            { rank: 32, score: 780, name: '', extra: { round: 1, stage: 1 } },
            { rank: 33, score: 770, name: '', extra: { round: 1, stage: 1 } },
            { rank: 34, score: 760, name: '', extra: { round: 1, stage: 1 } },
            { rank: 35, score: 750, name: '', extra: { round: 1, stage: 1 } },
            { rank: 36, score: 740, name: '', extra: { round: 1, stage: 1 } },
            { rank: 37, score: 730, name: '', extra: { round: 1, stage: 1 } },
            { rank: 38, score: 720, name: '', extra: { round: 1, stage: 1 } },
            { rank: 39, score: 710, name: '', extra: { round: 1, stage: 1 } },
            { rank: 40, score: 700, name: '', extra: { round: 1, stage: 1 } },
            { rank: 41, score: 690, name: '', extra: { round: 1, stage: 1 } },
            { rank: 42, score: 680, name: '', extra: { round: 1, stage: 1 } },
            { rank: 43, score: 670, name: '', extra: { round: 1, stage: 1 } },
            { rank: 44, score: 660, name: '', extra: { round: 1, stage: 1 } },
            { rank: 45, score: 650, name: '', extra: { round: 1, stage: 1 } },
            { rank: 46, score: 640, name: '', extra: { round: 1, stage: 1 } },
            { rank: 47, score: 630, name: '', extra: { round: 1, stage: 1 } },
            { rank: 48, score: 620, name: '', extra: { round: 1, stage: 1 } },
            { rank: 49, score: 610, name: '', extra: { round: 1, stage: 1 } },
            { rank: 50, score: 600, name: '', extra: { round: 1, stage: 1 } },
            { rank: 51, score: 590, name: '', extra: { round: 1, stage: 1 } },
            { rank: 52, score: 580, name: '', extra: { round: 1, stage: 1 } },
            { rank: 53, score: 570, name: '', extra: { round: 1, stage: 1 } },
            { rank: 54, score: 560, name: '', extra: { round: 1, stage: 1 } },
            { rank: 55, score: 550, name: '', extra: { round: 1, stage: 1 } },
            { rank: 56, score: 540, name: '', extra: { round: 1, stage: 1 } },
            { rank: 57, score: 530, name: '', extra: { round: 1, stage: 1 } },
            { rank: 58, score: 520, name: '', extra: { round: 1, stage: 1 } },
            { rank: 59, score: 510, name: '', extra: { round: 1, stage: 1 } },
            { rank: 60, score: 500, name: '', extra: { round: 1, stage: 1 } },
            { rank: 61, score: 490, name: '', extra: { round: 1, stage: 1 } },
            { rank: 62, score: 480, name: '', extra: { round: 1, stage: 1 } },
            { rank: 63, score: 470, name: '', extra: { round: 1, stage: 1 } },
            { rank: 64, score: 460, name: '', extra: { round: 1, stage: 1 } },
            { rank: 65, score: 450, name: '', extra: { round: 1, stage: 1 } },
            { rank: 66, score: 440, name: '', extra: { round: 1, stage: 1 } },
            { rank: 67, score: 430, name: '', extra: { round: 1, stage: 1 } },
            { rank: 68, score: 420, name: '', extra: { round: 1, stage: 1 } },
            { rank: 69, score: 410, name: '', extra: { round: 1, stage: 1 } },
            { rank: 70, score: 400, name: '', extra: { round: 1, stage: 1 } },
            { rank: 71, score: 390, name: '', extra: { round: 1, stage: 1 } },
            { rank: 72, score: 380, name: '', extra: { round: 1, stage: 1 } },
            { rank: 73, score: 370, name: '', extra: { round: 1, stage: 1 } },
            { rank: 74, score: 360, name: '', extra: { round: 1, stage: 1 } },
            { rank: 75, score: 350, name: '', extra: { round: 1, stage: 1 } },
            { rank: 76, score: 340, name: '', extra: { round: 1, stage: 1 } },
            { rank: 77, score: 330, name: '', extra: { round: 1, stage: 1 } },
            { rank: 78, score: 320, name: '', extra: { round: 1, stage: 1 } },
            { rank: 79, score: 310, name: '', extra: { round: 1, stage: 1 } },
            { rank: 80, score: 300, name: '', extra: { round: 1, stage: 1 } },
            { rank: 81, score: 290, name: '', extra: { round: 1, stage: 1 } },
            { rank: 82, score: 280, name: '', extra: { round: 1, stage: 1 } },
            { rank: 83, score: 270, name: '', extra: { round: 1, stage: 1 } },
            { rank: 84, score: 260, name: '', extra: { round: 1, stage: 1 } },
            { rank: 85, score: 250, name: '', extra: { round: 1, stage: 1 } },
            { rank: 86, score: 240, name: '', extra: { round: 1, stage: 1 } },
            { rank: 87, score: 230, name: '', extra: { round: 1, stage: 1 } },
            { rank: 88, score: 220, name: '', extra: { round: 1, stage: 1 } },
            { rank: 89, score: 210, name: '', extra: { round: 1, stage: 1 } },
            { rank: 90, score: 200, name: '', extra: { round: 1, stage: 1 } },
            { rank: 91, score: 190, name: '', extra: { round: 1, stage: 1 } },
            { rank: 92, score: 180, name: '', extra: { round: 1, stage: 1 } },
            { rank: 93, score: 170, name: '', extra: { round: 1, stage: 1 } },
            { rank: 94, score: 160, name: '', extra: { round: 1, stage: 1 } },
            { rank: 95, score: 150, name: '', extra: { round: 1, stage: 1 } },
            { rank: 96, score: 140, name: '', extra: { round: 1, stage: 1 } },
            { rank: 97, score: 130, name: '', extra: { round: 1, stage: 1 } },
            { rank: 98, score: 120, name: '', extra: { round: 1, stage: 1 } },
            { rank: 99, score: 110, name: '', extra: { round: 1, stage: 1 } },
        ],
    });
});
