import AbstractExtractor from "../AbstractExtractor";
import Extractor from "../Decorator/Extractor";

// Layout from hi2txt's definition (360 bytes), checked with npm run compare.
@Extractor({
    name: 'xmen'
})
export default class Xmen extends AbstractExtractor {
    protected charset = {
        0x1A: '0',
        0x1B: '1',
        0x1C: '2',
        0x1D: '3',
        0x1E: '4',
        0x1F: '5',
        0x20: '6',
        0x21: '7',
        0x22: '8',
        0x23: '9',
        0x24: '!',
        0x25: '?',
        0x26: ':',
        0x27: ',',
        0x28: '.',
        0x29: '-',
        0x2A: '·',
    };

    extract(): this {
        this.output.default.push(
            { rank: 1, score: parseInt(this.hi!.slice(58, 2).hexDigits()), name: this.hi!.slice(55, 3).toString(this.charset, 65) },
            { rank: 2, score: parseInt(this.hi!.slice(52, 2).hexDigits()), name: this.hi!.slice(49, 3).toString(this.charset, 65) },
            { rank: 3, score: parseInt(this.hi!.slice(46, 2).hexDigits()), name: this.hi!.slice(43, 3).toString(this.charset, 65) },
            { rank: 4, score: parseInt(this.hi!.slice(40, 2).hexDigits()), name: this.hi!.slice(37, 3).toString(this.charset, 65) },
            { rank: 5, score: parseInt(this.hi!.slice(34, 2).hexDigits()), name: this.hi!.slice(31, 3).toString(this.charset, 65) },
            { rank: 6, score: parseInt(this.hi!.slice(28, 2).hexDigits()), name: this.hi!.slice(25, 3).toString(this.charset, 65) },
            { rank: 7, score: parseInt(this.hi!.slice(22, 2).hexDigits()), name: this.hi!.slice(19, 3).toString(this.charset, 65) },
            { rank: 8, score: parseInt(this.hi!.slice(16, 2).hexDigits()), name: this.hi!.slice(13, 3).toString(this.charset, 65) },
            { rank: 9, score: parseInt(this.hi!.slice(10, 2).hexDigits()), name: this.hi!.slice(7, 3).toString(this.charset, 65) },
            { rank: 10, score: parseInt(this.hi!.slice(4, 2).hexDigits()), name: this.hi!.slice(1, 3).toString(this.charset, 65) },
            { rank: 11, score: parseInt(this.hi!.slice(118, 2).hexDigits()), name: this.hi!.slice(115, 3).toString(this.charset, 65) },
            { rank: 12, score: parseInt(this.hi!.slice(112, 2).hexDigits()), name: this.hi!.slice(109, 3).toString(this.charset, 65) },
            { rank: 13, score: parseInt(this.hi!.slice(106, 2).hexDigits()), name: this.hi!.slice(103, 3).toString(this.charset, 65) },
            { rank: 14, score: parseInt(this.hi!.slice(100, 2).hexDigits()), name: this.hi!.slice(97, 3).toString(this.charset, 65) },
            { rank: 15, score: parseInt(this.hi!.slice(94, 2).hexDigits()), name: this.hi!.slice(91, 3).toString(this.charset, 65) },
            { rank: 16, score: parseInt(this.hi!.slice(88, 2).hexDigits()), name: this.hi!.slice(85, 3).toString(this.charset, 65) },
            { rank: 17, score: parseInt(this.hi!.slice(82, 2).hexDigits()), name: this.hi!.slice(79, 3).toString(this.charset, 65) },
            { rank: 18, score: parseInt(this.hi!.slice(76, 2).hexDigits()), name: this.hi!.slice(73, 3).toString(this.charset, 65) },
            { rank: 19, score: parseInt(this.hi!.slice(70, 2).hexDigits()), name: this.hi!.slice(67, 3).toString(this.charset, 65) },
            { rank: 20, score: parseInt(this.hi!.slice(64, 2).hexDigits()), name: this.hi!.slice(61, 3).toString(this.charset, 65) },
            { rank: 21, score: parseInt(this.hi!.slice(178, 2).hexDigits()), name: this.hi!.slice(175, 3).toString(this.charset, 65) },
            { rank: 22, score: parseInt(this.hi!.slice(172, 2).hexDigits()), name: this.hi!.slice(169, 3).toString(this.charset, 65) },
            { rank: 23, score: parseInt(this.hi!.slice(166, 2).hexDigits()), name: this.hi!.slice(163, 3).toString(this.charset, 65) },
            { rank: 24, score: parseInt(this.hi!.slice(160, 2).hexDigits()), name: this.hi!.slice(157, 3).toString(this.charset, 65) },
            { rank: 25, score: parseInt(this.hi!.slice(154, 2).hexDigits()), name: this.hi!.slice(151, 3).toString(this.charset, 65) },
            { rank: 26, score: parseInt(this.hi!.slice(148, 2).hexDigits()), name: this.hi!.slice(145, 3).toString(this.charset, 65) },
            { rank: 27, score: parseInt(this.hi!.slice(142, 2).hexDigits()), name: this.hi!.slice(139, 3).toString(this.charset, 65) },
            { rank: 28, score: parseInt(this.hi!.slice(136, 2).hexDigits()), name: this.hi!.slice(133, 3).toString(this.charset, 65) },
            { rank: 29, score: parseInt(this.hi!.slice(130, 2).hexDigits()), name: this.hi!.slice(127, 3).toString(this.charset, 65) },
            { rank: 30, score: parseInt(this.hi!.slice(124, 2).hexDigits()), name: this.hi!.slice(121, 3).toString(this.charset, 65) },
            { rank: 31, score: parseInt(this.hi!.slice(238, 2).hexDigits()), name: this.hi!.slice(235, 3).toString(this.charset, 65) },
            { rank: 32, score: parseInt(this.hi!.slice(232, 2).hexDigits()), name: this.hi!.slice(229, 3).toString(this.charset, 65) },
            { rank: 33, score: parseInt(this.hi!.slice(226, 2).hexDigits()), name: this.hi!.slice(223, 3).toString(this.charset, 65) },
            { rank: 34, score: parseInt(this.hi!.slice(220, 2).hexDigits()), name: this.hi!.slice(217, 3).toString(this.charset, 65) },
            { rank: 35, score: parseInt(this.hi!.slice(214, 2).hexDigits()), name: this.hi!.slice(211, 3).toString(this.charset, 65) },
            { rank: 36, score: parseInt(this.hi!.slice(208, 2).hexDigits()), name: this.hi!.slice(205, 3).toString(this.charset, 65) },
            { rank: 37, score: parseInt(this.hi!.slice(202, 2).hexDigits()), name: this.hi!.slice(199, 3).toString(this.charset, 65) },
            { rank: 38, score: parseInt(this.hi!.slice(196, 2).hexDigits()), name: this.hi!.slice(193, 3).toString(this.charset, 65) },
            { rank: 39, score: parseInt(this.hi!.slice(190, 2).hexDigits()), name: this.hi!.slice(187, 3).toString(this.charset, 65) },
            { rank: 40, score: parseInt(this.hi!.slice(184, 2).hexDigits()), name: this.hi!.slice(181, 3).toString(this.charset, 65) },
            { rank: 41, score: parseInt(this.hi!.slice(298, 2).hexDigits()), name: this.hi!.slice(295, 3).toString(this.charset, 65) },
            { rank: 42, score: parseInt(this.hi!.slice(292, 2).hexDigits()), name: this.hi!.slice(289, 3).toString(this.charset, 65) },
            { rank: 43, score: parseInt(this.hi!.slice(286, 2).hexDigits()), name: this.hi!.slice(283, 3).toString(this.charset, 65) },
            { rank: 44, score: parseInt(this.hi!.slice(280, 2).hexDigits()), name: this.hi!.slice(277, 3).toString(this.charset, 65) },
            { rank: 45, score: parseInt(this.hi!.slice(274, 2).hexDigits()), name: this.hi!.slice(271, 3).toString(this.charset, 65) },
            { rank: 46, score: parseInt(this.hi!.slice(268, 2).hexDigits()), name: this.hi!.slice(265, 3).toString(this.charset, 65) },
            { rank: 47, score: parseInt(this.hi!.slice(262, 2).hexDigits()), name: this.hi!.slice(259, 3).toString(this.charset, 65) },
            { rank: 48, score: parseInt(this.hi!.slice(256, 2).hexDigits()), name: this.hi!.slice(253, 3).toString(this.charset, 65) },
            { rank: 49, score: parseInt(this.hi!.slice(250, 2).hexDigits()), name: this.hi!.slice(247, 3).toString(this.charset, 65) },
            { rank: 50, score: parseInt(this.hi!.slice(244, 2).hexDigits()), name: this.hi!.slice(241, 3).toString(this.charset, 65) },
            { rank: 51, score: parseInt(this.hi!.slice(358, 2).hexDigits()), name: this.hi!.slice(355, 3).toString(this.charset, 65) },
            { rank: 52, score: parseInt(this.hi!.slice(352, 2).hexDigits()), name: this.hi!.slice(349, 3).toString(this.charset, 65) },
            { rank: 53, score: parseInt(this.hi!.slice(346, 2).hexDigits()), name: this.hi!.slice(343, 3).toString(this.charset, 65) },
            { rank: 54, score: parseInt(this.hi!.slice(340, 2).hexDigits()), name: this.hi!.slice(337, 3).toString(this.charset, 65) },
            { rank: 55, score: parseInt(this.hi!.slice(334, 2).hexDigits()), name: this.hi!.slice(331, 3).toString(this.charset, 65) },
            { rank: 56, score: parseInt(this.hi!.slice(328, 2).hexDigits()), name: this.hi!.slice(325, 3).toString(this.charset, 65) },
            { rank: 57, score: parseInt(this.hi!.slice(322, 2).hexDigits()), name: this.hi!.slice(319, 3).toString(this.charset, 65) },
            { rank: 58, score: parseInt(this.hi!.slice(316, 2).hexDigits()), name: this.hi!.slice(313, 3).toString(this.charset, 65) },
            { rank: 59, score: parseInt(this.hi!.slice(310, 2).hexDigits()), name: this.hi!.slice(307, 3).toString(this.charset, 65) },
            { rank: 60, score: parseInt(this.hi!.slice(304, 2).hexDigits()), name: this.hi!.slice(301, 3).toString(this.charset, 65) },
        );
        return this;
    }
}
